### ISSUE TITLE
Updated weights from AnyGrasp

### ISSUE THREAD

**Issue by rlee3359** [graspnet/graspnet-baseline#49]
Hi, thanks for the code and interesting research! I found this repository via the AnyGrasp paper.

I am just wondering, how does this repository compare to the models used in that paper? Are the weights used in that paper available also? 

How can we reproduce the results and training process from that paper?

Thanks very much!

**Comment by Fang-Haoshu** [comment]
Hi, thanks for your interest! The AnyGrasp library and weight are released at anygrasp_sdk repo in this github organization. We are unable to provide the code at this point due to IP issue. But you can follow the code in graspness_unofficial https://github.com/graspnet/graspness_unofficial repo to try to reproduce the GSNet, It is easy to do so.
