### ISSUE TITLE
相机的坐标系要和夹爪的坐标系朝向保持一致吗？

### ISSUE THREAD

**Issue by xiaomi2077** [graspnet/graspnet-baseline#61]
你好，在将该算法部署在机器臂上时，我有一些疑问：
1、预训练模型预测出来的旋转矩阵，是相对于相机坐标系的吗？
2、如果是，是不是相机坐标系的xyz轴朝向要和[graspnetAPI](https://github.com/graspnet/graspnetAPI#grasp-definition)中定义的夹爪坐标系xyz轴朝向保持一致时，预测出来的旋转矩阵才能正常转换？
谢谢

**Comment by xiaomi2077** [comment]
谢谢你的回答。我在这个问题 https://github.com/graspnet/graspnet-baseline/issues/28#issue-975286317 里找到了解决办法。对预测出来的旋转矩阵点乘[0,0,1;1,0,0;0,1,0]后，就能转换到正确的姿态了。下面2个图，是我的夹爪的坐标和api里定义的夹爪坐标。
![image](https://github.com/graspnet/graspnet-baseline/assets/33375652/7781f400-f74f-4239-9db4-d3a0a57206a0)
![image](https://github.com/graspnet/graspnet-baseline/assets/33375652/896e3fe9-e01b-40cc-a992-414a7cd082e2)
[0,0,1;1,0,0;0,1,0] 这个矩阵应该就是你说的 `实际使用的夹爪坐标系和api里定义的夹爪坐标系的转换矩阵`

**Comment by gyt290811** [comment]
> 谢谢你的回答。我在这个问题 [#28 (comment)](https://github.com/graspnet/graspnet-baseline/issues/28#issue-975286317) 里找到了解决办法。对预测出来的旋转矩阵点乘[0,0,1;1,0,0;0,1,0]后，就能转换到正确的姿态了。下面2个图，是我的夹爪的坐标和api里定义的夹爪坐标。 ![image](https://private-user-images.githubusercontent.com/33375652/244357555-7781f400-f74f-4239-9db4-d3a0a57206a0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5MzU0OTUsIm5iZiI6MTcyMjkzNTE5NSwicGF0aCI6Ii8zMzM3NTY1Mi8yNDQzNTc1NTUtNzc4MWY0MDAtZjc0Zi00MjM5LTlkYjQtZDNhMGE1NzIwNmEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA2VDA5MDYzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQzYzRmYTc0NDY4ZTE5ZTViZTgxZWJlODA0NTEzNTlhYWY2ZDU4YzVlMGJjYWY2ZDE3M2ZhOWZkZTI5ZTc1NWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SXbrjCapUgapRJHdyu5Ot3de0bnfAzEYFoBeBcd78qg) ![image](https://private-user-images.githubusercontent.com/33375652/244357689-896e3fe9-e01b-40cc-a992-414a7cd082e2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5MzU0OTUsIm5iZiI6MTcyMjkzNTE5NSwicGF0aCI6Ii8zMzM3NTY1Mi8yNDQzNTc2ODktODk2ZTNmZTktZTAxYi00MGNjLWE5OTItNDE0YTdjZDA4MmUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA2VDA5MDYzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRkNThlMmYxMTkzMzIwYWJlYWZlM2RkZGEzYjZjMThiMWEwNTZmNDY2YmEyZjdhMTZhZTk3MjA1ZWUyM2NjOTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nGW79PMuS-Z78L5OgAYGf8ASRV56-d7Tt0hzbAeKKZQ) [0,0,1;1,0,0;0,1,0] 这个矩阵应该就是你说的 `实际使用的夹爪坐标系和api里定义的夹爪坐标系的转换矩阵`

我遇到了和你一摸一样的问题
你这是左乘还是右乘呀
是grasp pose * T还是T* grasp_pose

**Comment by zzc0053** [comment]
你好,我想问一下,你摄像机的坐标系和爪子的坐标系是一样的吗,不然是不是应该还要乘上摄像机到爪子的旋转矩阵?

**Comment by gyt290811** [comment]
我这设定的tool的坐标系朝向和相机的坐标系朝向是一致的，所以不用再乘



---- 回复的原邮件 ----
| 发件人 | Zhou ***@***.***> |
| 日期 | 2025年04月10日 11:07 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [graspnet/graspnet-baseline] 相机的坐标系要和夹爪的坐标系朝向保持一致吗？ (Issue #61) |

你好,我想问一下,你摄像机的坐标系和爪子的坐标系是一样的吗,不然是不是应该还要乘上摄像机到爪子的旋转矩阵?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you commented.Message ID: ***@***.***>

zzc0053 left a comment (graspnet/graspnet-baseline#61)

你好,我想问一下,你摄像机的坐标系和爪子的坐标系是一样的吗,不然是不是应该还要乘上摄像机到爪子的旋转矩阵?

**Comment by zzc0053** [comment]
兄弟,我还想问一下,预测出来的旋转矩阵R, 是左乘还是右乘, R@[0,0,1;1,0,0;0,1,0],还是[0,0,1;1,0,0;0,1,0]@R.

**Comment by gyt290811** [comment]
左乘，依次叠加



---- 回复的原邮件 ----
| 发件人 | Zhou ***@***.***> |
| 日期 | 2025年04月10日 13:10 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [graspnet/graspnet-baseline] 相机的坐标系要和夹爪的坐标系朝向保持一致吗？ (Issue #61) |

兄弟,我还想问一下,预测出来的旋转矩阵R, 是左乘还是右乘, ***@***.******@***.***

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you commented.Message ID: ***@***.***>

zzc0053 left a comment (graspnet/graspnet-baseline#61)

兄弟,我还想问一下,预测出来的旋转矩阵R, 是左乘还是右乘, ***@***.******@***.***

**Comment by anan-fighting** [comment]
> 谢谢你的回答。我在这个问题 [#28 (comment)](https://github.com/graspnet/graspnet-baseline/issues/28#issue-975286317) 里找到了解决办法。对预测出来的旋转矩阵点乘[0,0,1;1,0,0;0,1,0]后，就能转换到正确的姿态了。下面2个图，是我的夹爪的坐标和api里定义的夹爪坐标。 ![image](https://github.com/graspnet/graspnet-baseline/assets/33375652/7781f400-f74f-4239-9db4-d3a0a57206a0) ![image](https://github.com/graspnet/graspnet-baseline/assets/33375652/896e3fe9-e01b-40cc-a992-414a7cd082e2) [0,0,1;1,0,0;0,1,0] 这个矩阵应该就是你说的 `实际使用的夹爪坐标系和api里定义的夹爪坐标系的转换矩阵`

您好，我遇到了和你一样的问题，实测发现模型预测的X方向和我要预测的Z方向是反的，我左乘了[0,0,1;1,0,0;0,1,0]还是不对。

<img width="640" height="422" alt="Image" src="https://github.com/user-attachments/assets/941c2b37-480e-4849-8785-e10f2e222cfb" />

<img width="449" height="383" alt="Image" src="https://github.com/user-attachments/assets/a21abcc0-33b4-4e76-be4c-f79fe98f16b4" />

是不是这个模型预测的的夹爪往下的方向都是X+方向？
